Search curation on gene symbol
EBI-G2P/gene2phenotype_api pull request #43
Opened 2024-10-07 15:25 UTC by olaaustine

[G2P-263](https://www.ebi.ac.uk/panda/jira/browse/G2P-263)

2024-10-08 14:56 UTC, dglemos requested changes
These updates are affecting the other search types. The bug is in L193 (comment below).

2024-10-08 14:56 UTC, dglemos commented on gene2phenotype_project/gene2phenotype_app/views/search.py
> +                                            - draft
You could add: `draft (only available for authenticated users)`

2024-10-08 14:56 UTC, dglemos commented on gene2phenotype_project/gene2phenotype_app/views/search.py
> +        if serializer == "LocusGenotypeDisease.Serializer":
This is not working, when I search for type=gene the endpoint fails.
You should update this line to:
`if issubclass(serializer, LocusGenotypeDiseaseSerializer):`

2024-10-08 14:59 UTC, olaaustine commented on gene2phenotype_project/gene2phenotype_app/models.py
> +            models.Index(fields=["gene_symbol"])
Discussed physically, we are keeping it because it makes the search faster

2024-10-09 12:44 UTC, dglemos commented
The current search returns the following format:
```
{
            "id": "G2P03531",
            "gene": "ATM",
            "genotype": "monoallelic_autosomal",
            "disease": "ATM-related cancer",
            "panel": [
                "Cancer"
            ]
        }
```
For the draft, you should also return:
```
"genotype": "monoallelic_autosomal"
"disease": "ATM-related cancer"
```

2024-10-09 13:57 UTC, dglemos commented on gene2phenotype_project/gene2phenotype_app/views/search.py
> +                    "curator": c_data.user_name,
Sometimes, the username is not clear. It would be better to return First and Last name.

2024-10-09 18:10 UTC, olaaustine commented
> The current search returns the following format:
> 
> ```
> {
>             "id": "G2P03531",
>             "gene": "ATM",
>             "genotype": "monoallelic_autosomal",
>             "disease": "ATM-related cancer",
>             "panel": [
>                 "Cancer"
>             ]
>         }
> ```
> 
> For the draft, you should also return:
> 
> ```
> "genotype": "monoallelic_autosomal"
> "disease": "ATM-related cancer"
> "panel": [
>                 "Cancer"
>             ]
> ```

It now returns this 

```
{
            "id": "G2P03823",
            "gene": "TAC3",
            "date_created": "2024-08-08T14:08:26.046997Z",
            "date_last_updated": "2024-08-08T14:08:26.046997Z",
            "curator_first": null,
            "curator_last_name": null,
            "json_data": {
                "genotype": "",
                "disease": "",
                "panel": [
                    "Eye disorders",
                    "Skin disorders",
                    "Skeletal disorders"
                ]
            },
            "curator_email": "[dlemos@ebi.ac.uk](mailto:dlemos@ebi.ac.uk)"
        },
}
```
Let me know if you want me to add or remove stuff

2024-10-10 08:28 UTC, dglemos approved these changes
The endpoint works as expected.
I only have a comment about the key `json_data`, this is not necessary.

2024-10-10 08:31 UTC, olaaustine commented
> The endpoint works as expected. I only have a comment about the key `json_data`, this is not necessary.

okay do you want me to return it like this instead 
```
"genotype": "",
  "disease": "",
   "panel": [
                    "Eye disorders",
                    "Skin disorders",
                    "Skeletal disorders"
                ]
```

2024-10-10 08:37 UTC, olaaustine commented
> > The endpoint works as expected. I only have a comment about the key `json_data`, this is not necessary.
> 
> okay do you want me to return it like this instead
> 
> ```
> "genotype": "",
>   "disease": "",
>    "panel": [
>                     "Eye disorders",
>                     "Skin disorders",
>                     "Skeletal disorders"
>                 ]
> ```

Updated it to this 

```
{
            "id": "G2P03825",
            "gene": "TAC3",
            "date_created": "2024-08-09T09:24:31.517463Z",
            "date_last_updated": "2024-08-09T09:24:31.517463Z",
            "curator_first": null,
            "curator_last_name": null,
            "genotype": "",
            "disease_name": "MPI-related congenital disorder of glycosylation, type ib",
            "panels": [
                "Cancer disorders",
                "Skeletal disorders"
            ],
            "curator_email": "[dlemos@ebi.ac.uk](mailto:dlemos@ebi.ac.uk)"
  },
```

2024-10-10 08:40 UTC, dglemos commented
Thanks for the update. It looks good!

2024-10-10 09:57 UTC, merged